# Generated by Django 4.1 on 2022-09-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
